### ISSUE TITLE
Add an option to not filter useless pass statements

### ISSUE THREAD

**Issue by qyearsley-zz** [PyCQA/autoflake#10]
In [`fix_code`](https://github.com/myint/autoflake/blob/d98cffe094/autoflake.py#L386), `filter_useless_pass` is always called.

But, it would be nice to be able to remove unused import statements without modifying pass statements, and to control removal of pass statements separately.

**Comment by myint** [comment]
I think this is related to #9.

**Comment by qyearsley** [comment]
Ah, that's right! Yep, if that pull request can be modified to add pass statements where they're required when imports are removed, and also keep useless pass statements elsewhere, that would be what I had in mind with this issue.
