### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by johnthagen** [PyCQA/autoflake#108]
Wheels (`.whl`) for this package are [currently missing from PyPI](https://pypi.org/project/autoflake/1.4/#files). Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
````

**Comment by fsouza** [comment]
@myint I'd like to automate the integration with PyPI, but I wanted to check with you what's your preferred approach. Do you want to do the releases yourself? I could reuse a [workflow](https://github.com/cobrateam/splinter/blob/master/.github/workflows/upload-to-pypi.yml) I have in another project that I maintain, you wouldn't need to give me permission to release the package to PyPI, but only add a secret to this repo so I can reference it from the GH workflow. Are you ok with that? Or would you rather keep releasing it manually?

**Comment by myint** [comment]
I've just gone ahead and given you PyPI permissions.

**Comment by fsouza** [comment]
@myint thank you! Unfortunately I don't have permissions to add a secret to the repo, so automation won't be an option for now, but I can definitely push it manually as needed :)

**Comment by myint** [comment]
Try now.

**Comment by fsouza** [comment]
@myint that should work now, thank you very much!

**Comment by fsouza** [comment]
Confirmed it works here: https://github.com/PyCQA/autoflake/runs/8053824994?check_suite_focus=true

Next release should go out automatically \o/
