### ISSUE TITLE
config file option

### ISSUE THREAD

**Issue by GrozniyToaster** [PyCQA/autoflake#149]
I have  one .ini config for linters in my projects.  
Need option to specify this config, like `autoflake -r --config-file ../../tools/linter_configs.ini  src/lib/`
Example of .ini config:
```ini
[mypy]
show_error_codes = True
disallow_untyped_defs = True
warn_unreachable = True
warn_return_any = True

[autoflake]
remove-all-unused-imports=True

```

**Comment by fsouza** [comment]
Both setup.cfg and pyproject.toml are supposed to be a configuration file for linters in a project. Can you clarify the use case on why you need a different file?

**Comment by GrozniyToaster** [comment]
I need to specify a file that is not in the same directory and not in the parent (relative to the files being checked)

**Comment by GrozniyToaster** [comment]
🎉  We can close issue! 🎉  
What about minor release ?

**Comment by fsouza** [comment]
@GrozniyToaster let me just see if we can get #152 merged in the next day or two, and then I'll tag a new release. Thanks contributing!
