### ISSUE TITLE
why --remove-all-unused-imports  can't be recognized

### ISSUE THREAD

**Issue by yuxiaoqing66** [PyCQA/autoflake#157]
When I use "autoflake  --remove-all-unused-imports ." in git bush
It warns me:
Using both --remove-all and --imports is redundant
I don't know why it happens.
version: autoflake 1.7.0

**Comment by fsouza** [comment]
Do you have a configuration file?

**Comment by fsouza** [comment]
I believe this was also fixed by #170. Let me know if you're still seeing issues.
