### ISSUE TITLE
Removing import in __init__.py

### ISSUE THREAD

**Issue by jordan-bonecutter** [PyCQA/autoflake#169]
I have a python package with a structure like:

```
.
├── setup.py
└── mypackage
    ├── __init__.py
    └── mypackage.py

```

The contents of `__init__.py` are as follows:

```python3
from .mypackage import *
```

Autoflake is removing all contents from `__init__.py` breaking the package install. To fix the issue I'm asking autoflake to ignore `__init__.py`

**Comment by fsouza** [comment]
We can't have autoflake ignore __init__.py everywhere, as not everyone follows the same conventions. You have some options here:

1. add a `# noqa` comment to that line
2. invoke autoflake with `--exclude=__init__.py`

**Comment by jordan-bonecutter** [comment]
> We can't have autoflake ignore **init**.py everywhere, as not everyone follows the same conventions. You have some options here:
> 
> 1. add a `# noqa` comment to that line
> 2. invoke autoflake with `--exclude=__init__.py`

I have done that, though this is new behavior in 1.7.3. Reverting back to 1.7.0 leaves my import untouched. This seems like a breaking import removal IMO and autoflake shouldn't touch it (it broke my code at the very least, I imagine I'm not alone here)

**Comment by fsouza** [comment]
> > We can't have autoflake ignore **init**.py everywhere, as not everyone follows the same conventions. You have some options here:
> > 
> > 1. add a `# noqa` comment to that line
> > 2. invoke autoflake with `--exclude=__init__.py`
> 
> I have done that, though this is new behavior in 1.7.3. Reverting back to 1.7.0 leaves my import untouched. This seems like a breaking import removal IMO and autoflake shouldn't touch it (it broke my code at the very least, I imagine I'm not alone here)

Are you saying that `--exclude` didn't work? 🤔 Or that you didn't need `--exclude` before?

**Comment by jordan-bonecutter** [comment]
> > > We can't have autoflake ignore **init**.py everywhere, as not everyone follows the same conventions. You have some options here:
> > > 
> > > 1. add a `# noqa` comment to that line
> > > 2. invoke autoflake with `--exclude=__init__.py`
> > 
> > 
> > I have done that, though this is new behavior in 1.7.3. Reverting back to 1.7.0 leaves my import untouched. This seems like a breaking import removal IMO and autoflake shouldn't touch it (it broke my code at the very least, I imagine I'm not alone here)
> 
> Are you saying that `--exclude` didn't work? thinking Or that you didn't need `--exclude` before?

My bad, should have been more specific. `--exclude` works but I didn't need it before 1.7.3 for this specific file. I assume this is a new feature

**Comment by fsouza** [comment]
> My bad, should have been more specific. `--exclude` works but I didn't need it before 1.7.3 for this specific file. I assume this is a new feature

Gotcha, thanks for clarifying! Sounds like a regression then, it was definitely not intended. I'll investigate it.

**Comment by urtubia** [comment]
Hello! 
I'm running into a similar issue and I think this unittest shows the problem (I tested by including this test on `test_autoflake.py`)

```python
  def test_end_to_end_dont_remove_unused_imports_when_not_using_flag(self):
        with temporary_file(
            """\
from . import fake_bar
from . import fake_foo
fake_foo.fake_function()
""",
        ) as filename:
            process = subprocess.Popen(
                AUTOFLAKE_COMMAND
                + [
                    filename,
                ],
                stdout=subprocess.PIPE,
            )
            self.assertEqual(
                "",
                "\n".join(process.communicate()[0].decode().split(os.linesep)[3:]),
            )
```

I ran this test on different release labels and I noticed that it passed on `v1.7.1` and started failing on `v1.7.2`

**Comment by fsouza** [comment]
@urtubia thanks for sharing the reproducer. I see what's going on now. Fix coming soon.
