### ISSUE TITLE
`--ignore-pass-after-docstring` does not ignore pass when a newline comes in between

### ISSUE THREAD

**Issue by DenverCoder1** [PyCQA/autoflake#176]
When running autoflake with `--ignore-pass-after-docstring` the following `pass` gets removed even though it comes after a docstring. It seems to only be ignored currently if it specifically on the line after the """.

Example code:

```py
class MyException(Exception):
    """Example class

    This is an example docstring for the class.
    """

    pass
```

Expected: `pass` does not get removed

Actual behavior: autoflake removes the `pass`

**Comment by DenverCoder1** [comment]
I can create a fix for this if it's available

**Comment by fsouza** [comment]
@DenverCoder1 go for it! I'll likely not have a chance to work on this until next week.
