### ISSUE TITLE
Imports removed incorrectly with Generic class type annotation

### ISSUE THREAD

**Issue by DenverCoder1** [PyCQA/autoflake#178]
Example code where a used import is incorrectly removed by autoflake:

```py
from __future__ import annotations

from .scheduled_events import ScheduledEventUser

class _AsyncIterator(AsyncIterator[T]):
    ...

class ScheduledEventUserIterator(_AsyncIterator["ScheduledEventUser"]):
    ...
```

Expected: The `ScheduledEventUser` import should not be removed

Actual behavior: `ScheduledEventUser` gets removed even though it is used

(Source file for context - <https://github.com/nextcord/nextcord/blob/master/nextcord/iterators.py>)

**Comment by fsouza** [comment]
Hmmm that's surprising. I definitely have code in that style at work and don't run into this issue. I'll investigate it. Thanks for reporting!

**Comment by DenverCoder1** [comment]
Seems like this issue really belongs in pyflakes, since it seems that is where unused imports are detected.

**Comment by fsouza** [comment]
Oh ok I see why we don't run into this issue at work, we don't quote the values.

It looks like the issue with quoted values isn't really fixable: https://github.com/PyCQA/pyflakes/issues/571

**Comment by DenverCoder1** [comment]
I see, that looks like the same issue.

Wouldn't it be better to at least try to detect it, for example to check for an exact string match if future annotations is imported?

That may lead to false negatives in some rare cases, but I feel that would be much better than false positives since, as it is, it could break the code if unchecked.

**Comment by fsouza** [comment]
Isn't unquoting an option for you?

**Comment by DenverCoder1** [comment]
> Isn't unquoting an option for you?

Unfortunately, that's not so simple in this situation.

Without the quotes, it causes an error when building the docs:

```
NameError: name 'ScheduledEventUser' is not defined
```

If I take `ScheduledEventUser` out of the `if TYPE_CHECKING:` block, it causes other issues.

```
cannot import name 'Snowflake' from partially initialized module 'nextcord.abc'
(most likely due to a circular import) (nextcord/abc.py)
```

In other words, having the quotes seems necessary for the project to build properly.

**Comment by DenverCoder1** [comment]
I found that adding `# noqa: F401` works as a workaround to this issue, so I think that's the best option until there's some fix or partial fix that avoids the false positive.

**Comment by fsouza** [comment]
Gotcha, yeah I think that's our best option for now.
