### ISSUE TITLE
Way to ignore specific line

### ISSUE THREAD

**Issue by csm10495** [PyCQA/autoflake#184]
Is there a way to ignore a specific line (or region of code in a file) to not be processed by autoflake?

**Comment by fsouza** [comment]
You can add a `# noqa` comment: https://github.com/PyCQA/autoflake/blob/HEAD/README.md#excluding-specific-lines

**Comment by csm10495** [comment]
Thanks. Completely missed that somehow.

**Comment by fsouza** [comment]
@csm10495 no worries, it happens! 😁
