### ISSUE TITLE
--config does not work with project.toml

### ISSUE THREAD

**Issue by alexander-born** [PyCQA/autoflake#193]
When using `--config` a .cfg file is expected. It should also work with a pyproject.toml.

See
https://github.com/PyCQA/autoflake/blob/0373337022756fd930f01e6549a1b0a224e60376/autoflake.py#L1196

**Comment by phitoduck** [comment]
Was just about to open the same issue :D  Thanks for the good work you do making this awesome tool! It's seriously such a time saver.

My goal is to set up `pyproject.toml` as my single config file for all of my code quality tools. It's going well! I'm trying to get

1. Run the code-quality-tool commands individually
2. Run the code-quality-tool commands all at once using `pre-commit`
3. Run the code-quality-tool from `.vscode/settings.json`

I see that `autoflake` picks up `pyproject.toml` if you happen to execute the `autoflake` in the same directory as the `pyproject.toml`, however in my case my `pyproject.toml` is nested inside of my project.

Beyond `pyproject.toml`, I know some of the code-quality tools support arbitrary TOML file names (e.g. `pylint` could use `pylintrc.toml`)

**Comment by stasiekz** [comment]
@phitoduck 

As a workaround you can pass path to your `pyproject.toml` as an argument:

```
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    -   id: autoflake
        args: [--config=your_directory/pyproject.toml]
 ```
 
 And set all configuration options within `[autoflake]` section instead of '[tool.autoflake]' for instance:
 
 ```
 [autoflake]
check = true
remove-all-imports = true
```
