### ISSUE TITLE
Config is ignored when using --stdin-display-name

### ISSUE THREAD

**Issue by alexander-born** [PyCQA/autoflake#194]
STDIN_DISPLAY_NAME needs to be considered when searching for the config file.
See:
https://github.com/PyCQA/autoflake/blob/0373337022756fd930f01e6549a1b0a224e60376/autoflake.py#L1162

**Comment by alexander-born** [comment]
Sorry I am wrong, it does in fact consider the local config. I didn't correctly test it before.

**Comment by fsouza** [comment]
> Sorry I am wrong, it does in fact consider the local config. I didn't correctly test it before.

Thanks for confirming it!
