### ISSUE TITLE
Remove unused imports not working in place

### ISSUE THREAD

**Issue by beuleal** [PyCQA/autoflake#215]
Hi Folks,

I have created a sample python file and the results was:
```
╰─ autoflake --remove-all-unused-imports --in-place products.py
products.py: Unused imports/variables detected
```

products.py: copy was imported but not being used
```
import copy

class Products:
    name: str

    def __init__(self, name):
        self.name = name
```

___
Vesion:
```
╰─ autoflake --version
autoflake 2.0.0
```

**Comment by fsouza** [comment]
Hmmm, I can't repro. What version of Python are you running?

**Comment by beuleal** [comment]
```
╰─ python --version
Python 3.10.9

╰─ autoflake --version
autoflake 2.0.0
```

**Comment by fsouza** [comment]
Do you have a config file (`setup.cfg` or `pyproject.toml`)? I wonder if we have the wrong priority between flags and config files.

**Comment by beuleal** [comment]
Yes I do! Found the issue!

I have `pyproject.toml` with:
```
[tool.autoflake]
check = true
```

Removing this block solved my issue!
Thanks!

**Comment by kaminskypavel** [comment]
> Yes I do! Found the issue!
> 
> I have `pyproject.toml` with:
> 
> ```
> [tool.autoflake]
> check = true
> ```
> 
> Removing this block solved my issue! Thanks!

wish I could find it one hour earlier!
