### ISSUE TITLE
Removing import resorts imports in a way incompatible with isort

### ISSUE THREAD

**Issue by jakkdl** [PyCQA/autoflake#229]
isort sorts ALL_CAPS objects before other objects, while autoflake sorts purely lexically after removing an unused import object from a `from ... import ...` line - which causes discrepancies and means isort has to be run after autoflake in CI's.

#### initial file
```python
from typing import TYPE_CHECKING, Any, NamedTuple, TypeVar

if TYPE_CHECKING:
    T = TypeVar('T', bound=NamedTuple)
```
#### first line after running autoflake
```python
from typing import NamedTuple, TYPE_CHECKING, TypeVar
```
#### which then gets modified if we run isort afterwards
```python
from typing import TYPE_CHECKING, NamedTuple, TypeVar
```

I suggest this be solved either by adhering to isort's sorting order when removing an import - or not resorting the import objects at all when removing and entirely leaving that up to isort.

**Comment by jakkdl** [comment]
isort version: 5.12.0
autoflake version: 2.0.1
no config and no flags (other than `--in-place` for autoflake)

**Comment by fsouza** [comment]
@jakkdl can you give #232 a shot?
