### ISSUE TITLE
Why remove-all-unused-imports isn't default behavior?

### ISSUE THREAD

**Issue by xeon826** [PyCQA/autoflake#267]
I have this set in my pyproject.toml, and I see the doc states that there are cases that make this unsafe, can someone show me an example of code where this might break something?

**Comment by fsouza** [comment]
In Python, import a module executes code. If you have code that relies on import size effect, removing the import can break things.

Personally, I think that autoflake should still remove it, and users should use `# noqa` in cases like that, but I don't feel strongly enough about this to change the default. Changing defaults is always tricky.
