### ISSUE TITLE
Avoid copying `py.typed` into site-packages?

### ISSUE THREAD

**Issue by devdanzin** [PyCQA/autoflake#272]
In https://github.com/PyCQA/autoflake/commit/ab37b11eedfe25fd24fae9952e2ba8a9d7b928eb, a py.typed file was added and is automatically copied when installing autoflake. However, since autoflake installs directly to the site-packages directory, ISTM that this file applies to the whole contents of the directory, which can lead to unintended effects when typechecking unrelated code.

Would it be possible to exclude this file from installation?

**Comment by fsouza** [comment]
That's a good call out. I'll remove py.typed entirely. We should reintroduce it only if we move to a package style.
