### ISSUE TITLE
autoflake removing imports that are used inside eval() function 

### ISSUE THREAD

**Issue by Saksham573001** [PyCQA/autoflake#301]
I have a code in python where i am executing code inside eval like this `eval(str(code_config.get("condition")))`  now inside my conditions i am using some constant that is imported above the file but autoflake is removing that import as it doesn't consider what can be used inside eval. Please fix this issue if you have the bandwidth.

**Comment by fsouza** [comment]
There's nothing we can do in this case, please add a `# noqa` to the import line to have autoflake ignore it.

We could try to parse the string passed to eval, but there are no guarantees that that string is available statically, and I'd rather not go that route.
