### ISSUE TITLE
Add support for config file

### ISSUE THREAD

**Issue by ljades** [PyCQA/autoflake#59]
Can we have the ability to set up a config in a `setup.cfg` (which also helps it run in tandem with flake8's configuration) for which parts of the autolinter we want to run by default?

**Comment by nameer** [comment]
Hi, any update on this?

**Comment by qci-amos** [comment]
There is a workaround: https://github.com/quwac/pyproject-autoflake

**Comment by ChihweiLHBird** [comment]
Support config in `pyproject.toml` is another option. Wondering if there is any update on this issue.

**Comment by ed-wright** [comment]
Hi All, autoflake 1.5.0 now supports configuration via pyproject.toml or setup.cfg [https://github.com/PyCQA/autoflake#configuration](https://github.com/PyCQA/autoflake#configuration)

**Comment by fsouza** [comment]
Oh I had missed this, @ed-wright thanks for bringing it up!
