### ISSUE TITLE
unused module flagged in python3 but not python2

### ISSUE THREAD

**Issue by leoll2** [PyCQA/autoflake#85]
Consider this trivial file `foo.py` with just one line:
```
import signal
```
The module is clearly unused, so it should be flagged by autoflake.  
On my platform, I installed autoflake with both pip2 and pip3, apparently the same version:
```
leoll2:~ > python2 -m autoflake --version
autoflake 1.4

leoll2:~ > python3 -m autoflake --version
autoflake 1.4
```

However, their behaviour is different when I execute autoflake on foo.py:

```
leoll2:~ > python2 -m autoflake foo.py		-> outputs nothing

leoll2:~ > python3 -m autoflake foo.py 
--- original/foo.py
+++ fixed/foo.py
@@ -1 +0,0 @@
-import signal

leoll2:~ > python2 -m autoflake --remove-all-unused-imports foo.py 
--- original/foo.py
+++ fixed/foo.py
@@ -1 +0,0 @@
-import signal
```
As you can see, Python 2 autoflake does not flag `signal` as unused unless I add the flag `--remove-all-unused-imports`. I observe the same behavior with other modules like `enum`, but not for `os` and `math`. As far as I know, `signal` is part of the py2 standard library, unlike enum which was backported from py3, so I would expect autoflake to mark this import as unused in both versions, regardless of the Python version.

Can anyone explain, please?

**Comment by fsouza** [comment]
Closing as this was a py2-only bug, and Python 2 is no longer supported.
